guanli/guanli/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from guan.views import *

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', index,name="index"),
    url(r'^see/$', see,name='see'),
    url(r'^update/$', update,name='update'),
    url(r'^zenjia/$', zenjia,name="zengjia"),
]

guanli/guan/models.py
#coding:utf8
from django.db import models

# Create your models here.

class guan(models.Model):
    num = models.IntegerField("房间号码",unique=True)
    tex = models.ForeignKey('tex',verbose_name='房型')
    ceng = models.ForeignKey("ceng",verbose_name='楼层')
    zhuangtai = models.ForeignKey("zhuangtai",verbose_name="房间状态")
    jiage = models.IntegerField('房间价格')
    class Meta:
        verbose_name="酒店管理"
        verbose_name_plural=verbose_name
    def __unicode__(self):
        return str(self.num)

class tex(models.Model):
    choose=(
        (u'单人房',u'单人房'),
        (u'普通大床房',u'普通大床房'),
        (u'豪华大床房',u'豪华大床房'),
        (u'商务双床房',u'商务双床房'),
        )
    name =models.CharField(choices=choose,max_length=40)
    def __unicode__(self):
        return self.name

class ceng(models.Model):
    choose1 =(
        (u"1",u"1"),
        (u"2",u"2"),
        (u"3",u"3"),
        (u"4",u"4"),
    )
    name = models.CharField(choices=choose1,max_length=40)
    def __unicode__(self):
        return self.name
class zhuangtai(models.Model):
     choose2 = (
        (u"住净",u"住净"),
        (u"空净",u"空净"),
        (u"空脏",u"空脏"),
        (u"住脏",u"住脏"),
    )
     name = models.CharField(choices=choose2,max_length=40)
     def __unicode__(self):
        return self.name

guanli/guan/views.py
from django.shortcuts import render,HttpResponseRedirect,HttpResponse
import models
# Create your views here.
def index(req):
    guanli = models.guan.objects.all()
    try:
        guanli_id=req.GET.get('guan_id')
        if guanli_id:
            guanli_id=int(guanli_id)
            models.guan.objects.get(id=guanli_id).delete()
    except Exception,e:
        print e
    return render(req,"index.html",locals())
def zenjia(req):
    if req.method == "GET":
        texs = models.tex.objects.all()
        return render(req,"zenjia.html",locals())
    else:
        tex_x =models.tex.objects.get(id=req.POST.get("tex"))
        ceng_x = models .ceng.objects.get(name=req.POST.get("ceng"))
        zhuangtai_x = models.zhuangtai.objects.get(name=req.POST.get("zhuangtai"))
        models.guan.objects.create(
        num =req.POST.get("num"),
        tex = tex_x,
        ceng = models.ceng.objects.get(id=ceng_x.id),
        zhuangtai = models.zhuangtai.objects.get(id=zhuangtai_x.id),
        jiage = req.POST.get("jiage"),
        )
        return HttpResponseRedirect("/")

def update(req):
    if req.method == "GET":
        allroom = models.guan.objects.all()
        texs = models.tex.objects.all()
        return render(req,"update.html",locals())
    else:
        num =req.POST.get("num")
        tex_x =models.tex.objects.get(id=req.POST.get("tex"))
        ceng_x = models .ceng.objects.get(name=req.POST.get("ceng"))
        zhuangtai_x = models.zhuangtai.objects.get(name=req.POST.get("zhuangtai"))
        room_obj = models.guan.objects.get(num=num)
        room_obj.num = req.POST.get("num")
        room_obj.tex = tex_x
        room_obj.ceng = models.ceng.objects.get(id=ceng_x.id)
        room_obj.zhuangtai = models.zhuangtai.objects.get(id=zhuangtai_x.id)
        room_obj.jiage = req.POST.get("jiage")
        room_obj.save()
        return HttpResponseRedirect("/")

def see(req):
    room_type = models.tex.objects.all()
    return render(req,"see.html",locals())

guanli/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>酒店管理</title>
</head>
<body>
<table align="center" style="margin-top:100px">
<tr>
    <td><a href="/zenjia"><input type="submit" value="增加房间信息"> </a></td>
    <td><a href="/update"><input type="submit" value="修改房间信息"> </a></td>
    <td><a href="/see"><input type="submit" value="查询统计信息"> </a></td>
</tr>
</table>
<table border="1px" align="center" cellspacing="0">
    <tr  >
        <th></th>
        <th>房间号码</th>
        <th>房间类型</th>
        <th>楼层</th>
        <th>房间状态</th>
        <th>房间价格</th>
        <th></th>
    </tr>
    {% for guanli in guanli %}
        <tr>
        <td><input name="sex" type="radio" value="{{ guanli.id }}"></td>
        <td>{{ guanli.num }}</td>
        <td>{{ guanli.tex }}</td>
        <td>{{ guanli.ceng }}</td>
        <td>{{ guanli.zhuangtai }}</td>
        <td>{{ guanli.jiage }}</td>
        <td><a href="/?guan_id={{ guanli.id }}"><input type="submit" value="删除"></a></td>
        </tr>
    {% endfor %}

  </table>
</body>
</html>

guanli/templates/see.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<table border="1px">

<tr>
    <th>房间类型</th>
    <th>数量</th>
</tr>
    {% for room in room_type %}
    <tr>
        <td>{{ room.name }}</td>
        <td>{{ room.guan_set.select_related.count }}</td>
    </tr>
    {% endfor %}


</table>

</body>
</html>

guanli/templates/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<br><h3 align="center">修改房间信息</h3>
<hr>

<table align="center">
    <form action="/update/" method="POST">{% csrf_token %}
    <tr>
        <td>房间号码</td>
        <td>
            <select name="num">
                {% for foo in allroom %}
                <option value="{{ foo.num }}" >{{ foo.num }}</option>
                {% endfor %}
            </select>
        </td>
    </tr>
     <tr>
        <td>房型</td>
        <td>
            <select name="tex">
                {% for tex in texs %}
                <option value="{{ tex.id }}" >{{ tex.name }}</option>
                {% endfor %}
            </select>
        </td>
    </tr>
    <tr>
        <td>楼层</td>
        <td><select name="ceng">
            <option>1</option>
            <option>2</option>
            <option>3</option>
            <option>4</option>
        </select></td>
    </tr>
    <tr>
        <td>房间状态</td>
        <td><select name="zhuangtai">
            <option>住净</option>
            <option>空净</option>
            <option>空脏</option>
            <option>住脏</option>
        </select></td>
    </tr>
      <tr>
        <td>价格</td>
        <td><input type="text" name="jiage"></td>
      </tr>
    <tr>
        <td><input type="submit" value="保存"></td>
    </tr>
</form>
</table>

</body>
</html>

guanli/templates/zenjia.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<br><h3 align="center">增加房间信息</h3>
<hr>

<table align="center">
    <form action="/zenjia/" method="POST">{% csrf_token %}
    <tr>
        <td>房间号码</td>
        <td><input type="text" name="num"></td>
    </tr>
     <tr>
        <td>房型</td>
        <td>
            <select name="tex">
                {% for tex in texs %}
                <option value="{{ tex.id }}" >{{ tex.name }}</option>
                {% endfor %}
            </select>
        </td>
    </tr>
    <tr>
        <td>楼层</td>
        <td><select name="ceng">
            <option>1</option>
            <option>2</option>
            <option>3</option>
            <option>4</option>
        </select></td>
    </tr>
    <tr>
        <td>房间状态</td>
        <td><select name="zhuangtai">
            <option>住净</option>
            <option>空净</option>
            <option>空脏</option>
            <option>住脏</option>
        </select></td>
    </tr>
      <tr>
        <td>价格</td>
        <td><input type="text" name="jiage"></td>
      </tr>
    <tr>
        <td><input type="submit" value="保存"></td>
    </tr>
</form>
</table>

</body>
</html>